; /////////////////////////////////////////////////////////////////////////
; ///                                                                   ///
; /// >>> SSAVCALL Manager - MultiTask Part Of the SSAVCALL Project <<< ///
; ///                                                                   ///
; /// Another KOSS Production 1998 for ATARI with at least a 68020 CPU  ///
; /// SSAVMANA wont run without SSAVCALL                                ///
; ///                                                                   ///
; /////////////////////////////////////////////////////////////////////////

	output	SSAVMANA.ACC
	
	include	MODULES\MANA\ACCSTART.SSM
	
	
	
	